# Generated by Django 4.1 on 2023-02-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='message',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
